services:
  postgres:
    image: postgres
    
    ports:
      - "5433:5432"

    environment:
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD}
      POSTGRES_DB: ${CSE_312_DB}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LOCAL_DB_USER} -d ${CSE_312_DB}"]
      interval: 1s
      timeout: 5s
      retries: 20
      start_period: 0s

  app:
    build: .

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      LOCAL_DB_USER: ${LOCAL_DB_USER}
      LOCAL_DB_PASSWORD: ${LOCAL_DB_PASSWORD}
      LOCAL_DB: ${CSE_312_DB}

    ports:
      - "8080:8080"